# Also change the version in README.md and extra below
site_url: https://www.openhasp.com/0.6.3/
edit_uri: https://github.com/HASwitchPlate/openHASP-docs/edit/0.6.3/docs/

repo_url: https://github.com/HASwitchPlate/openHASP
repo_name: HASwitchPlate/openHASP

site_name: "openHASP"
site_description: "Open firmware for MCUs to drive a low-cost commodity touch display"
site_author: "Francis Van Roie"
copyright: Copyright &copy; 2019 - 2021 Francis Van Roie and contributors

extra:
  openhasp:
    version: 0.6.3

  social:
    - icon: material/github
      link: https://github.com/HASwitchPlate/openHASP/discussions
      name: GitHub Discussions
    - icon: material/discord
      link: https://discord.gg/VCWyuhF
      name: Discord Chat
    - icon: material/home-assistant
      link: https://community.home-assistant.io/t/openhasp-an-mqtt-driven-touchscreen-scene-controller/300853
      name: Home Assistant Forum

  version:
    provider: mike
    default: 0.6

#   alternate:
#     - name: Default (en)
#       link: ./
#       lang: en

#     # Switch to English
#     - name: English
#       link: ./en/
#       lang: en

#     # Switch to Dutch
#     - name: Nederlands
#       link: ./nl/
#       lang: nl
# nav:
#
# !!! The Navigation bar is built from the contents of the `.pages` files in each directory !!!

      
theme:
  logo: "assets/images/logo.png"
  favicon: favicon.ico
  icon:
    repo: fontawesome/brands/github
  name: material
  custom_dir: custom_theme
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Light mode
  features:
    - navigation.instant # When this is enabled the $(document).ready(function() won't run from youtube.js!
    - navigation.tracking
    #    - navigation.tabs
    #    - navigation.tabs.sticky
    #    - navigation.sections
    #    - navigation.expand
    - search.suggest
    - search.highlight
    - navigation.top

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.highlight:
  #      linenums: true
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.striphtml:
      strip_comments: true
      strip_js_on_attributes: false
  - toc:
      permalink: "~"
      toc_depth: 3
  - markdown_include.include:
      base_path: docs

plugins:
  - table-reader
  - search
  - git-revision-date
  - awesome-pages:
      strict: false
  - markdownextradata:
      jinja_options:
        variable_start_string: "{<"
        variable_end_string: ">}"
        block_start_string: "{<%"
        block_end_string: "%>}"
        comment_start_string: "{<#"
        comment_end_string: "#>}"
  # - i18n:
  #     default_language: en
  #     languages:
  #       en: English
  #       nl: Nederlands
  #     nav_translations:
  #       nl:
  #         Home: Thuis
  #         Design: Ontwerp
  #         Pages: Pagina's
  #         Objects: Objecten
  #         Styling: Stijleigenschappen
  #         Fonts: Lettertypen
  #         Commands: Commando's
