name: MkDocs

on: push

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install --upgrade setuptools==57.4.0
          python -m pip install -r requirements.txt

      - name: Build docs
        run: |
          mkdocs build

      # - name: Validate generated HTML files
      #   run: |
      #     docker run -v $(pwd):/test --rm wjdp/htmltest --conf .htmltest.yml
      # # On push to master or release branch, deploy docs

      - name: Set up git author
        # if: github.ref == 'refs/heads/0.5' || startsWith(github.ref, 'refs/heads/release/v')
        run: |
          remote_repo="https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote rm origin
          git remote add origin "${remote_repo}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch pages
        run: |
          git fetch origin gh-pages --verbose

      # Uncomment this action if dev needs to be present
      - name: Delete dev tag
        run: |
          mike delete "dev"
        continue-on-error: true

      - name: Set default
        run: |
          mike set-default "latest"

      - name: Deploy docs 0.5
        if: github.ref == 'refs/heads/0.5'
        run: |
          mike deploy "0.5" --title="0.5.2" --config-file "${GITHUB_WORKSPACE}/mkdocs.yml" --push --rebase
        # env:
        #   CUSTOM_DOMAIN: docs.haswitchplate.com

      - name: Deploy docs 0.6
        if: github.ref == 'refs/heads/0.6'
        run: |
          mike deploy "0.6" --title="0.6.0" --config-file "${GITHUB_WORKSPACE}/mkdocs.yml" --push --rebase

      - name: Deploy docs 0.6.1
        if: github.ref == 'refs/heads/0.6.1'
        run: |
          mike deploy --update-aliases "0.6.1" --title="0.6.1" --config-file "${GITHUB_WORKSPACE}/mkdocs.yml" --push --rebase

      - name: Deploy docs 0.6.2
        if: github.ref == 'refs/heads/0.6.2'
        run: |
          mike deploy --update-aliases "0.6.2" latest --title="0.6.2" --config-file "${GITHUB_WORKSPACE}/mkdocs.yml" --push --rebase

      - name: List
        run: |
          mike list

        # env:
        #   CUSTOM_DOMAIN: docs.haswitchplate.com

      # - name: Deploy docs (Self-hosted)
      #   if: startsWith(github.ref, 'refs/heads/release/v')        
      #   run: |
      #     git fetch origin gh-pages --verbose
      #     mike deploy ${GITHUB_REF##*/release/} -t "Self-hosted ${GITHUB_REF##*/release/}" --config-file "${GITHUB_WORKSPACE}/mkdocs.yml" --push --rebase
