name: MkDocs

on: push

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
  
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: Set up git author
        run: |
          remote_repo="https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote rm origin
          git remote add origin "${remote_repo}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch pages
        run: |
          git fetch origin gh-pages --verbose

      - name: Fetch Firmware
        if: github.ref == 'refs/heads/0.6.2'
        uses: robinraju/release-downloader@v1.2
        with:
          repository: "HASwitchPlate/openHASP"
          tag: "v0.6.2"
          fileName: "*"
          out-file-path: "docs/assets/firmware"

      - name: Release docs website and API reference
        run: |
          poetry run mike deploy --push --update-aliases ${RELEASE_TAG_VERSION} latest
          poetry run mike set-default --push latest

      - name: List
        run: |
          mike list

        # env:
        #   CUSTOM_DOMAIN: docs.haswitchplate.com

      # - name: Deploy docs (Self-hosted)
      #   if: startsWith(github.ref, 'refs/heads/release/v')        
      #   run: |
      #     git fetch origin gh-pages --verbose
      #     mike deploy ${GITHUB_REF##*/release/} -t "Self-hosted ${GITHUB_REF##*/release/}" --config-file "${GITHUB_WORKSPACE}/mkdocs.yml" --push --rebase
